### ISSUE TITLE
无法浏览网页

### ISSUE THREAD

**Issue by Feng999** [ayqy/browser#1]
您好，看到该组件后第一时间进行了安装体验，但是安装完之后，通过命令 open Browser 可以打开窗口，但是输入网之后无法浏览网页。

系统：macOS Catalina 10.15.1
VSCode: 1.41.1

**Comment by ayqy** [comment]
- 检查输入的URL是否正确，`http://`协议不能省略
- 检查网络，能够正常连接外网
- 关闭VPN或全局代理
- 尝试 http://www.example.com 等常规网址，看能否正常打开

如果还不能解决，请提供一个出现问题的网址

**Comment by Feng999** [comment]
因为省略了 https 协议导致的~

**Comment by 78zhanghao87** [comment]
有同样的问题
本地npm服务
系统：windows7 64bit
VSCode: 1.42.1
http://192.168.1.224:8342
http://localhost:8342

**Comment by Stabaoc** [comment]
https://weread.qq.com/ 好像就不行
